### ISSUE TITLE
v7.12.0 update throws AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided at assertValidNodeInfo 

### ISSUE THREAD

**Issue by connorsmallman** [yannickcr/eslint-plugin-react#2095]
v7.12.0 is throws the following error 
```
> eslint --ext .jsx,.js src/ etc/

AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (/node_modules/eslint/lib/util/report-translator.js:96:9)
    at args (/node_modules/eslint/lib/util/report-translator.js:246:9)
    at Object.report (/node_modules/eslint/lib/linter.js:720:41)
    at reportUndeclaredPropTypes (/node_modules/eslint-plugin-react/lib/rules/prop-types.js:175:17)
    at Program:exit.Object.keys.filter.forEach.component (/node_modules/eslint-plugin-react/lib/rules/prop-types.js:193:11)
    at Array.forEach (<anonymous>)
    at Object.Program:exit (/node_modules/eslint-plugin-react/lib/rules/prop-types.js:192:81)
    at updatedRuleInstructions.(anonymous function) (/node_modules/eslint-plugin-react/lib/util/Components.js:754:75)
    at listeners.(anonymous function).forEach.listener (/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
```

**Comment by jeffrigby** [comment]
I'm seeing this too. I use react-router which passes location and match as props. When I compare the location search, it throws this error:

```js
  componentDidUpdate(prevProps) {
    const { match, location} = this.props;
    const searchEquals = prevProps.location.search === location.search;
  }
```

**Comment by ljharb** [comment]
Closed in #2099.

**Comment by nicofrand** [comment]
Hi,

I am still getting this issue with 7.12.**1**. Am I the only one? I made sure the package was updated correctly.

Thanks for all the hard work!

**Comment by nicofrand** [comment]
I narrowed it down to this file: https://framagit.org/kresusapp/kresus/blob/master/client/components/lazyLoader.js

Thanks for reopening.

**Comment by johnpmitsch** [comment]
@ljharb we are hitting this as well and updating eslint-plugin-react to use master fixes it. When do you anticipate https://github.com/yannickcr/eslint-plugin-react/commit/4da90ea19f805cb8e67523a983c2352aab144783 will land in a release?

**Comment by ljharb** [comment]
More than 9 hours after I’ve merged it, I’m sure.

Releases, as always, are done when a maintainer has time, and can’t be done any faster.

**Comment by johnpmitsch** [comment]
@ljharb thanks for the update. Just to clarify, I wasn't trying to be pushy, I was just curious as the error is blocking our automation and we can take other steps if a release isn't planned in the near future. Apologies if it came off that way

**Comment by ljharb** [comment]
I’ll try to find time today.

**Comment by remcohaszing** [comment]
I am still getting this error using eslint-plugin-react@7.12.2.

The following code is triggering the error:

```jsx
import React from 'react';

export default class extends React.Component {
  onSubmit = () => {
    this.setState((state, { a }) => {
      a.b.c();
      return null;
    });
  };

  render() {
    return null;
  }
}
```

**Comment by nicofrand** [comment]
Mine was fixed with 7.12.2, many thanks!

**Comment by ljharb** [comment]
@remcohaszing can you please file a new issue?

**Comment by connorsmallman** [comment]
Thanks @ljharb

**Comment by the-spyke** [comment]
I've got this error with `7.12.3` and this code:
```js
import React from "react";

export default class Controller extends React.Component {
    handleAdd = id => {
        this.setState((state, { name }) => {
            const item = this.buildtem(id);
        });
    };
}
```

**Comment by ljharb** [comment]
@the-spyke please file that as a new issue, and we’ll fix it asap

**Comment by JustFly1984** [comment]
Yes, it is fixed for me in v7.12.4

**Comment by huixisheng** [comment]
```
  "resolutions": {
    "eslint": "7.12.1",
    "eslint-config-airbnb-typescript": "^12.0.0",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "@typescript-eslint/eslint-plugin": "^4.6.0"
  },
```
It fixed.

**Comment by ljharb** [comment]
I'm not sure why that would fix it, but either way, resolutions isn't an npm feature, and overriding dependency versions is not a good idea.

**Comment by randyou** [comment]
```
{
  // note you must disable the base rule as it can report incorrect errors
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": ["error"]
}
```

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md
